### PR TITLE
Antimatter Typescript Edition

### PR DESCRIPTION
**Pull request by iacore**
I want to annotate antimatter.js in idiomatic Typescript.

Maybe it's better if we work on this together in this repo?

### CODE REVIEW

**Comment by toomim** [comment]
Since Greg & I prefer Javascript to Typescript, perhaps it'd be best to just create a new `antimatter_ts/` folder to hold this typescript version of the code? Or perhaps just have all the files within the same folder, without deleting the .js files?

**Comment by iacore** [comment]
A new folder is fine. I wish antimatter has come with Typescript hints, so I can understand its algorithms easier. Currently I have to do trial and error in Node.

**Comment by toomim** [comment]
Ok, cool. I want to prioritize getting the code more understandable! Having another style of implementation is a great step toward that. If the typescript ends up being easier to understand (and still works) then we should switch to that. Another path forward, though, is recruit @dglittle's help in making the Javascript version simpler to understand. He wrote most (or all?) of that code.

**Comment by iacore** [comment]
@dglittle @toomim 

Would a compromise to be using JSDoc to annotate types?

Move by svelte to switch from Typescript to JSDoc: https://github.com/sveltejs/svelte/pull/8569

Some form of a tutorial: https://dev.to/mirzaleka/learn-how-to-document-javascripttypescript-code-using-jsdoc-typedoc-359h

**Pull request merged**
