### PR TITLE
Make exports work for es6 modules

### PR DESCRIPTION
**Pull request by canadaduane**
Maybe merge this if we want to, but it probably needs a wider discussion around where files should go and how we should split things so we can import the default export (instead of named exports).

### CODE REVIEW

**Comment by toomim** [comment]
I read the redfin article, and don't yet see a need to avoid named exports. I'd love to see if you encountered a reason that I'm not privy to. In any case, I'm reorganizing the braidjs code at a large scale right now, and am going to try to make it work with both `import` and `require`.

**Comment by canadaduane** [comment]
So the main issue I was encountering was that you had changed `module.exports = braid_fetch` to `module.exports = { fetch: braid_fetch, http: braidify_http }`, without updating `package/esm-index.js`. The result was an import in Ribbon that couldn't resolve `fetch`.

I *think* that we can still get this to work with named exports on the commonjs side, but a single unnamed import on the `esm-index.js` side:

```js
// http-client.js
module.exports = {fetch: braid_fetch, http: braidify_http}
```

```js
// package/esm-index.js
 import client from '../protocols/http/http-client.js' 

export { fetch: client.fetch, http: client.http }
```

This might work?

**Comment by toomim** [comment]
I think this is now superceded by https://github.com/braid-org/braidjs/commit/7915b7d2a5b48243355d49f06fcc2ce2761602c6

**Comment by canadaduane** [comment]
I'll close this and open a new one if I encounter anything. Thanks!

**Pull request closed without merging**
